### PR TITLE
Cleanup and simplification of code structure (Suggestion)

### PR DESCRIPTION
**Pull request by hernot**
Hi Paul

Finally i managed to come up with a suggestion for simplifying and cleaning code structure such that future extensions are simple and easy and that dropping python2 support is nearly as simple as removing related code sections from core.py. And converting some other places marked with TODO back to proper and clean python >= 3 code.

Here a short summary on the changes the elaborate details you find in the commit message.
Admitted some codes may still need some comments and doc strings.

- All parsing now only handled by grammar.py file including parsing of AmiraMesh data-streams
- HyperSurface data structure is parsed along with File header removing asymmetry between HyperSurface and AmiraMesh file trees
- HyperSurface data-streams are loaded along with structure information unless stream_loading set to HEADER_ONLY or False in that case not loaded at all
- Added functions for defining and modifying global stream_loading behaviour, possible values are HEADERONLY, ONDEMMAND (current default open to discussion), IMMEDIATE. Can be overridden by load_streams argument of Header and AmiraFile classes
- AmiraFile is subclass of Header not Wrapper
- introduced Meta array_declarations which allow proper mapping of BoundaryCurves, Patches and Surfaces declarations on HyperSurface Files
- Extended AmiraDispatchProcessor to group lists of array_declarations which share same base name and differ only be integer counter using meta_array_declarations. Can be in future be extended by more complex and sophisticated heuristics for deciding whether grouping is valid or should not happen. Example could be HxSpreadSheet files.
- Improved access to attributes added using add_attr, no more need for falling back to getattr exempt for loading of data streams on demand
- parent attribute is now weak reference with automatic resetting to None if parent is deleted
- some metaclass magic to flag attributes declared on slots to be read-only when accessed from outside Block class or subclass.
- renamed decodesmodule.cpp to decodersmodule.c skipping static_cast method which was only one requiring to compile as c++ which caused compiler error when compiling for python2
- all tests should be running ok for python3 and python2 as long as still valid all others currently commented. please verify.
- extended lists of relative imports by `if __package__: else: ``clause switching between relative import if imported from external ahds package or called from within ahds directory for debugging purpose. In contrast to `try: catch:` these work for python2 and python3 flawlessly
- in core.py changed your assert statement based argument checks back to simple if based checks as asserts are converted to no-ops if python is called with -O or -OO options for basic optimizations. And than check always succeeds. Should not rely on people playing fair and using code properly or not ask python for optimization.
- first suggestion on how to identify and support various ContentTypes especially from AmiraMesh files see suggestion for implementation using HxSpreadSheet as an example.

### CODE REVIEW

**Comment by hernot** [comment]
Think Travis setup for python2 i have no idea what the pywavelets package is used for it is not inside installation requirements. Are they really needed or could they for python 2 be kicked. 
For python 3 i fixed it by limiting scicit-image to <= 0.15 one more as for python 2.7 Results for python3.6 and python3.7 are working after undoing some temporary direct debugging hack. 
For testcoverage we should make a plan how to best cover the new stuff. 

Will continue to improve this pullrequest, if i come across something while working on other project which could be beneficial for ahds, or further simplify things.

**Comment by hernot** [comment]
List of packages which in latest version do not support anything below Python 3.5 or even 3.6 again increased. Fear that till end of first quarter of 2020 we will do nothing else any more than identifying latest package versions of indirect dependencies still supporting Python 2.7. This time Pillow stopped support for Python 2.7 starting with version 7.0.0.

**Comment by hernot** [comment]
Seems last weekend Travis was on maintenance as it did not run

**Comment by hernot** [comment]
Any idea why Travis not running?

**Comment by hernot** [comment]
Any idea why Travis not running?

**Comment by hernot** [comment]
Not sure why pytest hicksup on Python 3.5 possibly cause tarvis.net is not any more hosted and we should switcht finally to tarvis.com. What ever the reason is i do not have any idea. 

Despite from that, added unit tests and tests to achieve 100 % coverage for core modules only extra is not tested at all these tests you have to do.

There are serveral lines which i marked with nocover for one of the following reasons
1) unless code broken else where not reached -> Exception if executed
2) lack of test data to be able to check if correct or should throw execption if code broken ->
    warning if executed remembering to collect test data triggering line and recording what
    has happened to reach there
3) exclusively relevant for Python 2 or Python >= 3 marked with cover_py2 or cover_py3

**EDIT**: pathlib2 required by pytest for python < 3.6 tries to compare three element list `sys.version_info` with two element tuple which is valid and possible on Python2 but not Python3 fear to fix this would require to open related issue on pytest which would be rejected anyway ([see](https://github.com/pytest-dev/pytest/issues/5017)). Alternative drop python3.5 testing on travis to avoid pytest switchback to pathlib2 for python3.5. How much installations of ahds you would expect to break if not tested under python3.5? I will remove for now as the only fix i could come up with.

**Comment by paulkorir** [comment]
Hi Christoph,
I'm very happy to merge these. I would like to suggest some cleanup:
- squash commits so that we don't have 'oh no!' commits
- make the commit message helpful
Thanks so much for your contribution.
Paul

**Comment by hernot** [comment]
Hi Paul
good to hear from you. Yes same procedure as every time. Maybe, if i encounter some more things to make less complicated hassl i will do in addition. But i think i have all so far.

**Comment by hernot** [comment]
Unless Travis finds some packages which meanwhile dropped python2 or python3.5 support squashing should be done and commit message should be updated accordingly.

**Comment by hernot** [comment]
Thank you very much even though i meant that you just update dev with your changes from master related to travis moving to .com only,so that i can than amend pull request before you merge it finally.

**Comment by paulkorir** [comment]
We ran out of free travis credits and I don't have the bandwidth to figure it out. Therefore, I've got things working with Gihub actions. We can then unmerge your changes then you can simply copy the `.github` folder and make the necessary changes to get the tests running. Is that OK?

**Comment by hernot** [comment]
Sure would have been easier to just put the file in dev, cause thatn it would have fetched the changes and force pushed them back to my fork but no worry. I already have fetched the updated master and the updated dev so is unmerge stil necessary or which files did you change to make github actions work, maybe i can merge over to dev on my fork and than pullrequest against upstream dev. Would assumably easier than unmerging again.

**Comment by paulkorir** [comment]
That's OK. I'll find a workaround.

**Pull request merged**
